CREATE TYPE genre AS ENUM ('Technology','Investment');

DROP TABLE IF EXISTS users cascade;

CREATE TABLE users (
  userid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  fn TEXT NOT NULL,
  ln TEXT NOT NULL,
  dob DATE NOT NULL,
  email TEXT NOT NULL
);

DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
  post_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  userid INTEGER NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  type genre NOT NULL,
  date_posted TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT posts_fk
    FOREIGN KEY(userid)
      REFERENCES users(userid)
);

DROP TABLE IF EXISTS comments;

CREATE TABLE comments (
  comment_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  userid INTEGER NOT NULL,
  post_id INTEGER NOT NULL,
  comment TEXT NOT NULL,
  comment_date TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT comments_fk
    FOREIGN KEY(post_id)
      REFERENCES posts(post_id)
  CONSTRAINT user_comments_fk
    FOREIGN KEY(userid)
      REFERENCES users(userid)
);